# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW-14' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW-14
  pod 'RealmSwift', '=10.1.4'
  pod 'Alamofire'
end
